# Using indicators with pandas assin

In [ ]:
from mintalib.samples import sample_prices
from mintalib.indicators import ROC, EMA, SMA, MACD, ATR, RSI

prices = sample_prices()
prices

                  open        high         low       close     volume
date
1980-12-12    0.098298    0.098725    0.098298    0.098298  469033600
1980-12-15    0.093597    0.093597    0.093169    0.093169  175884800
1980-12-16    0.086758    0.086758    0.086331    0.086331  105728000
1980-12-17    0.088468    0.088895    0.088468    0.088468   86441600
1980-12-18    0.091032    0.091460    0.091032    0.091032   73449600
...                ...         ...         ...         ...        ...
2026-04-20  270.329987  274.279999  270.290009  273.049988   36590200
2026-04-21  271.500000  272.799988  265.399994  266.170013   50209800
2026-04-22  267.820007  273.739990  266.869995  273.170013   43249200
2026-04-23  275.049988  275.769989  271.649994  273.429993   33399600
2026-04-24  272.760010  273.059998  269.649994  271.059998   38124500

[11433 rows x 5 columns]

In [11]:
prices.assign(roc=ROC(1))

,open,high,low,close,volume,roc
date,,,,,,
1980-12-12,0.098298,0.098725,0.098298,0.098298,469033600,NaN
1980-12-15,0.093597,0.093597,0.093169,0.093169,175884800,-0.052171
1980-12-16,0.086758,0.086758,0.086331,0.086331,105728000,-0.073398
1980-12-17,0.088468,0.088895,0.088468,0.088468,86441600,0.024750
1980-12-18,0.091032,0.091460,0.091032,0.091032,73449600,0.028992
...,...,...,...,...,...,...
2026-04-20,270.329987,274.279999,270.290009,273.049988,36590200,0.010435
2026-04-21,271.500000,272.799988,265.399994,266.170013,50209800,-0.025197
2026-04-22,267.820007,273.739990,266.869995,273.170013,43249200,0.026299
2026-04-23,275.049988,275.769989,271.649994,273.429993,33399600,0.000952
2026-04-24,272.760010,273.059998,269.649994,271.059998,38124500,-0.008668